name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pip
  - pygit2
  - python
  - sphinx
  - pip:
    - configparser
    - sphinx_rtd_theme
    - robpol86_sphinxcontrib_googleanalytics
    - sphinxcontrib_bibtex
    - sphinxcontrib_spelling
    
